package com.alfa.shakegroan.ui

import com.alfa.shakegroan.data.AppLanguage

data class AppStrings(
    val home: String,
    val settings: String,
    val upload: String,
    val profile: String,
    val sounds: String,
    val fall: String,
    val slap: String,
    val sensitivity: String,
    val volume: String,
    val language: String,
    val appLanguage: String,
    val mySounds: String,
    val library: String,
    val addSound: String,
    val extractFromVideo: String,
    val record: String,
    val uploadFile: String,
    val chooseVideo: String,
    val chooseAnotherVideo: String,
    val trimCurrentFragment: String,
    val save: String,
    val cancel: String,
    val name: String,
    val titleLabel: String,
    val trimHelp: String,
    val fragment: String,
    val buildingWaveform: String,
    val pressToRecord: String,
    val recording: String,
    val firstLaunchTitle: String,
    val firstLaunchText: String,
    val open: String,
    val later: String,
    val modeUnavailable: String,
    val modeOn: String,
    val modeOff: String,
    val guideTitle: String,
    val guideBody: String,
    val guideAndDescription: String,
    val installWidget: String,
    val soundSavedNotice: String,
    val deleteSoundTitle: String,
    val deleteSoundMessage: String,
    val deleteSoundAction: String,
) {
    companion object {
        fun forLanguage(language: AppLanguage): AppStrings = when (language) {
            AppLanguage.RU -> ru
            AppLanguage.ES -> base.copy(
                home = "Inicio",
                settings = "Ajustes",
                upload = "Carga",
                profile = "Perfil",
                sounds = "Sonidos",
                fall = "Caída",
                slap = "Palmada",
                sensitivity = "Sensibilidad",
                volume = "Volumen",
                language = "Idioma",
                appLanguage = "Idioma de la app",
                mySounds = "Mis sonidos",
                library = "Biblioteca",
                addSound = "+ añadir sonido",
                extractFromVideo = "Extraer de vídeo",
                record = "Grabar",
                uploadFile = "Subir",
                chooseVideo = "Elegir vídeo",
                chooseAnotherVideo = "Elegir otro vídeo",
                trimCurrentFragment = "Recortar fragmento actual",
                save = "Guardar",
                cancel = "Cancelar",
                name = "nombre",
                titleLabel = "Nombre",
                trimHelp = "Mueve los controles para editar",
                fragment = "Fragmento",
                buildingWaveform = "Creando onda...",
                pressToRecord = "Toca para grabar",
                recording = "Grabando %s",
                firstLaunchTitle = "¡NO TE APURES!",
                firstLaunchText = "Para no arruinar la primera impresión de la app, lee la instrucción corta.",
                open = "Abrir",
                later = "Luego",
                modeUnavailable = "modo no disponible",
                modeOn = "modo activado",
                modeOff = "modo desactivado",
                guideTitle = "Instrucción",
                guideBody = """
                    1. Prueba la «Sensibilidad». Los sensores se comportan distinto según el teléfono. Si bajas la sensibilidad al mínimo, ese efecto se apaga por completo.

                    2. Añade tus propios sonidos sin límites. Puedes grabarlos, subirlos desde el teléfono en casi cualquier formato o extraer audio de un video, como un clip descargado o una grabación de pantalla, y editarlo.

                    3. Puedes instalar un widget para activar y desactivar los efectos rápidamente.

                    4. Si algo no funciona o no va como esperabas, no te apresures a dejar una mala reseña: escríbenos y resolveremos el problema. Es nuestra primera app 🙂
                """.trimIndent(),
                guideAndDescription = "Instrucción",
                installWidget = "Instalar widget",
                soundSavedNotice = "Sonido guardado. Aparecerá en Ajustes cuando elijas un sonido.",
                deleteSoundTitle = "¿Eliminar sonido?",
                deleteSoundMessage = "Este sonido se eliminará de Mis sonidos. No se puede deshacer.",
                deleteSoundAction = "Eliminar",
            )
            AppLanguage.IT -> base.copy(
                home = "Home",
                settings = "Impostazioni",
                upload = "Carica",
                profile = "Profilo",
                sounds = "Suoni",
                fall = "Caduta",
                slap = "Schiaffo",
                sensitivity = "Sensibilità",
                volume = "Volume",
                language = "Lingua",
                appLanguage = "Lingua app",
                mySounds = "I miei suoni",
                library = "Libreria",
                addSound = "+ aggiungi suono",
                extractFromVideo = "Estrai da video",
                record = "Registra",
                uploadFile = "Carica",
                chooseVideo = "Scegli video",
                chooseAnotherVideo = "Scegli un altro video",
                trimCurrentFragment = "Taglia frammento attuale",
                save = "Salva",
                cancel = "Annulla",
                name = "nome",
                titleLabel = "Nome",
                trimHelp = "Muovi i cursori per modificare",
                fragment = "Frammento",
                buildingWaveform = "Creo onda...",
                pressToRecord = "Tocca per registrare",
                recording = "Registrazione %s",
                firstLaunchTitle = "NON AVERE FRETTA!",
                firstLaunchText = "Per non rovinare la prima impressione dell’app, leggi la breve istruzione.",
                open = "Apri",
                later = "Dopo",
                modeUnavailable = "modalità non disponibile",
                modeOn = "modalità attiva",
                modeOff = "modalità disattiva",
                guideTitle = "Istruzione",
                guideBody = """
                    1. Prova la «Sensibilità». I sensori cambiano comportamento da telefono a telefono. Se abbassi la sensibilità al minimo, quell’effetto si spegne del tutto.

                    2. Aggiungi suoni senza limiti. Puoi registrarli, caricarli dal telefono in quasi qualsiasi formato o estrarre audio da un video, come una clip scaricata o una registrazione schermo, e modificarlo.

                    3. Puoi installare un widget per accendere e spegnere rapidamente gli effetti.

                    4. Se qualcosa non funziona o sembra sbagliato, non lasciare subito una recensione negativa: scrivici e risolveremo il problema. È la nostra prima app 🙂
                """.trimIndent(),
                guideAndDescription = "Istruzione",
                installWidget = "Installa widget",
                soundSavedNotice = "Suono salvato. Apparirà nelle impostazioni quando scegli un suono.",
                deleteSoundTitle = "Eliminare il suono?",
                deleteSoundMessage = "Questo suono verrà rimosso dai tuoi suoni. L’azione non può essere annullata.",
                deleteSoundAction = "Elimina",
            )
            AppLanguage.PT_BR -> base.copy(
                home = "Início",
                settings = "Configurações",
                upload = "Enviar",
                profile = "Perfil",
                sounds = "Sons",
                fall = "Queda",
                slap = "Tapa",
                sensitivity = "Sensibilidade",
                volume = "Volume",
                language = "Idioma",
                appLanguage = "Idioma do app",
                mySounds = "Meus sons",
                library = "Biblioteca",
                addSound = "+ adicionar som",
                extractFromVideo = "Extrair do vídeo",
                record = "Gravar",
                uploadFile = "Enviar",
                chooseVideo = "Escolher vídeo",
                chooseAnotherVideo = "Escolher outro vídeo",
                trimCurrentFragment = "Cortar fragmento atual",
                save = "Salvar",
                cancel = "Cancelar",
                name = "nome",
                titleLabel = "Nome",
                trimHelp = "Mova os controles para editar",
                fragment = "Fragmento",
                buildingWaveform = "Criando onda...",
                pressToRecord = "Toque para gravar",
                recording = "Gravando %s",
                firstLaunchTitle = "NÃO TENHA PRESSA!",
                firstLaunchText = "Para não estragar a primeira impressão do app, leia a instrução curta.",
                open = "Abrir",
                later = "Depois",
                modeUnavailable = "modo indisponível",
                modeOn = "modo ligado",
                modeOff = "modo desligado",
                guideTitle = "Instrução",
                guideBody = """
                    1. Teste a «Sensibilidade». Os sensores podem se comportar de formas diferentes em cada telefone. Se você reduzir a sensibilidade ao mínimo, esse efeito será desativado por completo.

                    2. Adicione seus sons sem limites. Você pode gravar, enviar do telefone em quase qualquer formato ou extrair áudio de um vídeo, como um clipe baixado ou gravação de tela, e editar.

                    3. Você pode instalar um widget para ligar e desligar os efeitos rapidamente.

                    4. Se algo não funcionar ou parecer errado, não deixe uma avaliação ruim logo de cara: escreva para nós e vamos resolver. Este é nosso primeiro app 🙂
                """.trimIndent(),
                guideAndDescription = "Instrução",
                installWidget = "Instalar widget",
                soundSavedNotice = "Som salvo. Ele aparecerá nas configurações ao escolher um som.",
                deleteSoundTitle = "Excluir som?",
                deleteSoundMessage = "Este som será removido dos seus sons. Esta ação não pode ser desfeita.",
                deleteSoundAction = "Excluir",
            )
            AppLanguage.DE -> base.copy(
                home = "Start",
                settings = "Einstellungen",
                upload = "Upload",
                profile = "Profil",
                sounds = "Sounds",
                fall = "Sturz",
                slap = "Klaps",
                sensitivity = "Empfindlichkeit",
                volume = "Lautstärke",
                language = "Sprache",
                appLanguage = "App-Sprache",
                mySounds = "Meine Sounds",
                library = "Bibliothek",
                addSound = "+ Sound hinzufügen",
                extractFromVideo = "Aus Video extrahieren",
                record = "Aufnehmen",
                uploadFile = "Hochladen",
                chooseVideo = "Video wählen",
                chooseAnotherVideo = "Anderes Video wählen",
                trimCurrentFragment = "Aktuelles Fragment schneiden",
                save = "Speichern",
                cancel = "Abbrechen",
                name = "name",
                titleLabel = "Name",
                trimHelp = "Bewege die Regler zum Bearbeiten",
                fragment = "Fragment",
                buildingWaveform = "Wellenform wird erstellt...",
                pressToRecord = "Zum Aufnehmen tippen",
                recording = "Aufnahme %s",
                firstLaunchTitle = "NICHT HETZEN!",
                firstLaunchText = "Damit der erste Eindruck der App gut bleibt, lies kurz die Anleitung.",
                open = "Öffnen",
                later = "Später",
                modeUnavailable = "Modus nicht verfügbar",
                modeOn = "Modus ein",
                modeOff = "Modus aus",
                guideTitle = "Anleitung",
                guideBody = """
                    1. Probiere die «Empfindlichkeit» aus. Sensoren verhalten sich je nach Telefon unterschiedlich. Wenn du die Empfindlichkeit ganz nach unten stellst, wird dieser Effekt komplett ausgeschaltet.

                    2. Füge eigene Sounds ohne Limit hinzu. Du kannst aufnehmen, fast jedes Format vom Telefon hochladen oder Audio aus einem Video extrahieren, etwa aus einem Download oder einer Bildschirmaufnahme, und es bearbeiten.

                    3. Du kannst ein Widget installieren, um Effekte schnell ein- und auszuschalten.

                    4. Wenn etwas nicht funktioniert oder falsch wirkt, hinterlasse bitte nicht sofort eine schlechte Bewertung: Schreib uns, und wir lösen das Problem. Das ist unsere erste App 🙂
                """.trimIndent(),
                guideAndDescription = "Anleitung",
                installWidget = "Widget installieren",
                soundSavedNotice = "Sound gespeichert. Er erscheint in den Einstellungen, wenn du einen Sound auswählst.",
                deleteSoundTitle = "Sound löschen?",
                deleteSoundMessage = "Dieser Sound wird aus deinen Sounds entfernt. Das kann nicht rückgängig gemacht werden.",
                deleteSoundAction = "Löschen",
            )
            AppLanguage.FR -> base.copy(
                home = "Accueil",
                settings = "Réglages",
                upload = "Import",
                profile = "Profil",
                sounds = "Sons",
                fall = "Chute",
                slap = "Claque",
                sensitivity = "Sensibilité",
                volume = "Volume",
                language = "Langue",
                appLanguage = "Langue de l’app",
                mySounds = "Mes sons",
                library = "Bibliothèque",
                addSound = "+ ajouter un son",
                extractFromVideo = "Extraire d’une vidéo",
                record = "Enregistrer",
                uploadFile = "Importer",
                chooseVideo = "Choisir une vidéo",
                chooseAnotherVideo = "Choisir une autre vidéo",
                trimCurrentFragment = "Couper le fragment actuel",
                save = "Enregistrer",
                cancel = "Annuler",
                name = "nom",
                titleLabel = "Nom",
                trimHelp = "Déplace les curseurs pour modifier",
                fragment = "Fragment",
                buildingWaveform = "Création de l’onde...",
                pressToRecord = "Touchez pour enregistrer",
                recording = "Enregistrement %s",
                firstLaunchTitle = "NE TE PRÉCIPITE PAS !",
                firstLaunchText = "Pour ne pas gâcher ta première impression de l’app, lis la courte instruction.",
                open = "Ouvrir",
                later = "Plus tard",
                modeUnavailable = "mode indisponible",
                modeOn = "mode activé",
                modeOff = "mode désactivé",
                guideTitle = "Instruction",
                guideBody = """
                    1. Essaie la «Sensibilité». Les capteurs peuvent réagir différemment selon le téléphone. Si tu baisses la sensibilité au minimum, cet effet se désactive complètement.

                    2. Ajoute tes sons sans limite. Tu peux enregistrer, importer presque n’importe quel format depuis ton téléphone ou extraire l’audio d’une vidéo, comme une vidéo téléchargée ou un enregistrement d’écran, puis le modifier.

                    3. Tu peux installer un widget pour activer et désactiver rapidement les effets.

                    4. Si quelque chose ne marche pas ou semble incorrect, ne laisse pas tout de suite un mauvais avis : écris-nous et nous réglerons le problème. C’est notre première app 🙂
                """.trimIndent(),
                guideAndDescription = "Instruction",
                installWidget = "Installer le widget",
                soundSavedNotice = "Son enregistré. Il apparaîtra dans les réglages au moment de choisir un son.",
                deleteSoundTitle = "Supprimer le son ?",
                deleteSoundMessage = "Ce son sera supprimé de vos sons. Cette action est irréversible.",
                deleteSoundAction = "Supprimer",
            )
            AppLanguage.JA -> base.copy(
                home = "ホーム",
                settings = "設定",
                upload = "追加",
                profile = "プロフィール",
                sounds = "サウンド",
                fall = "落下",
                slap = "叩き",
                sensitivity = "感度",
                volume = "音量",
                language = "言語",
                appLanguage = "アプリの言語",
                mySounds = "マイサウンド",
                library = "ライブラリ",
                addSound = "+ サウンドを追加",
                extractFromVideo = "動画から抽出",
                record = "録音",
                uploadFile = "アップロード",
                chooseVideo = "動画を選択",
                chooseAnotherVideo = "別の動画を選択",
                trimCurrentFragment = "現在の部分をトリム",
                save = "保存",
                cancel = "キャンセル",
                name = "名前",
                titleLabel = "名前",
                trimHelp = "スライダーを動かして編集",
                fragment = "範囲",
                buildingWaveform = "波形を作成中...",
                pressToRecord = "タップして録音",
                recording = "録音 %s",
                firstLaunchTitle = "急がないで！",
                firstLaunchText = "アプリの第一印象を悪くしないために、短い使い方を読んでください。",
                open = "開く",
                later = "あとで",
                modeUnavailable = "利用不可",
                modeOn = "オン",
                modeOff = "オフ",
                guideTitle = "使い方",
                guideBody = """
                    1. 「感度」を試してください。センサーの反応は端末によって異なります。感度を最小にすると、その効果は完全にオフになります。

                    2. 自分のサウンドを制限なく追加できます。録音、端末内のほぼ任意の形式のファイル、ダウンロード動画や画面録画から抽出した音声を追加し、編集できます。

                    3. ウィジェットを追加すると、効果をすばやくオン・オフできます。

                    4. うまく動かない場合や期待と違う場合は、悪いレビューの前にぜひ連絡してください。問題を解決します。これは私たちの最初のアプリです 🙂
                """.trimIndent(),
                guideAndDescription = "使い方",
                installWidget = "ウィジェットを追加",
                soundSavedNotice = "サウンドを保存しました。設定でサウンドを選ぶと表示されます。",
                deleteSoundTitle = "サウンドを削除しますか？",
                deleteSoundMessage = "このサウンドはマイサウンドから削除されます。元に戻せません。",
                deleteSoundAction = "削除",
            )
            AppLanguage.KO -> base.copy(
                home = "홈",
                settings = "설정",
                upload = "업로드",
                profile = "프로필",
                sounds = "사운드",
                fall = "낙하",
                slap = "찰싹",
                sensitivity = "감도",
                volume = "볼륨",
                language = "언어",
                appLanguage = "앱 언어",
                mySounds = "내 사운드",
                library = "라이브러리",
                addSound = "+ 사운드 추가",
                extractFromVideo = "동영상에서 추출",
                record = "녹음",
                uploadFile = "업로드",
                chooseVideo = "동영상 선택",
                chooseAnotherVideo = "다른 동영상 선택",
                trimCurrentFragment = "현재 구간 자르기",
                save = "저장",
                cancel = "취소",
                name = "이름",
                titleLabel = "이름",
                trimHelp = "슬라이더를 움직여 편집하세요",
                fragment = "구간",
                buildingWaveform = "파형 생성 중...",
                pressToRecord = "탭하여 녹음",
                recording = "녹음 %s",
                firstLaunchTitle = "서두르지 마세요!",
                firstLaunchText = "앱의 첫인상을 망치지 않도록 짧은 안내를 읽어주세요.",
                open = "열기",
                later = "나중에",
                modeUnavailable = "모드 사용 불가",
                modeOn = "모드 켜짐",
                modeOff = "모드 꺼짐",
                guideTitle = "안내",
                guideBody = """
                    1. «감도»를 조절해 보세요. 휴대폰마다 센서 반응이 다릅니다. 감도를 최소로 내리면 해당 효과가 완전히 꺼집니다.

                    2. 원하는 소리를 제한 없이 추가할 수 있습니다. 녹음, 거의 모든 형식의 파일 업로드, 다운로드 영상이나 화면 녹화에서 오디오 추출 후 편집이 가능합니다.

                    3. 위젯을 설치하면 효과를 빠르게 켜고 끌 수 있습니다.

                    4. 무언가 작동하지 않거나 이상하면 나쁜 리뷰를 남기기 전에 알려주세요. 문제를 해결하겠습니다. 이 앱은 저희의 첫 앱입니다 🙂
                """.trimIndent(),
                guideAndDescription = "안내",
                installWidget = "위젯 설치",
                soundSavedNotice = "사운드가 저장되었습니다. 설정에서 사운드를 선택할 때 표시됩니다.",
                deleteSoundTitle = "사운드를 삭제할까요?",
                deleteSoundMessage = "이 사운드는 내 사운드에서 삭제됩니다. 되돌릴 수 없습니다.",
                deleteSoundAction = "삭제",
            )
            AppLanguage.HI -> base.copy(
                home = "होम",
                settings = "सेटिंग्स",
                upload = "अपलोड",
                profile = "प्रोफ़ाइल",
                sounds = "ध्वनियाँ",
                fall = "गिरना",
                slap = "थप्पड़",
                sensitivity = "संवेदनशीलता",
                volume = "वॉल्यूम",
                language = "भाषा",
                appLanguage = "ऐप भाषा",
                mySounds = "मेरी ध्वनियाँ",
                library = "लाइब्रेरी",
                addSound = "+ ध्वनि जोड़ें",
                extractFromVideo = "वीडियो से निकालें",
                record = "रिकॉर्ड",
                uploadFile = "अपलोड",
                chooseVideo = "वीडियो चुनें",
                chooseAnotherVideo = "दूसरा वीडियो चुनें",
                trimCurrentFragment = "मौजूदा हिस्सा काटें",
                save = "सेव",
                cancel = "रद्द",
                name = "नाम",
                titleLabel = "नाम",
                trimHelp = "संपादन के लिए स्लाइडर खिसकाएँ",
                fragment = "हिस्सा",
                buildingWaveform = "वेवफॉर्म बना रहा है...",
                pressToRecord = "रिकॉर्ड करने के लिए टैप करें",
                recording = "रिकॉर्डिंग %s",
                firstLaunchTitle = "जल्दी मत करें!",
                firstLaunchText = "ऐप का पहला अनुभव खराब न हो, इसलिए छोटी गाइड पढ़ लें.",
                open = "खोलें",
                later = "बाद में",
                modeUnavailable = "मोड उपलब्ध नहीं",
                modeOn = "मोड चालू",
                modeOff = "मोड बंद",
                guideTitle = "निर्देश",
                guideBody = """
                    1. «संवेदनशीलता» आज़माएँ। अलग-अलग फोन में सेंसर अलग तरह से काम कर सकते हैं। संवेदनशीलता को न्यूनतम करने पर वह प्रभाव पूरी तरह बंद हो जाएगा।

                    2. अपनी ध्वनियाँ बिना सीमा जोड़ें। आप रिकॉर्ड कर सकते हैं, फोन से लगभग किसी भी फॉर्मेट में अपलोड कर सकते हैं, या डाउनलोड किए गए वीडियो/स्क्रीन रिकॉर्डिंग से ऑडियो निकालकर संपादित कर सकते हैं।

                    3. प्रभावों को जल्दी चालू/बंद करने के लिए विजेट लगाया जा सकता है।

                    4. अगर कुछ काम नहीं करता या अजीब लगता है, तो खराब समीक्षा देने से पहले हमें लिखें। हम समस्या हल करेंगे। यह हमारा पहला ऐप है 🙂
                """.trimIndent(),
                guideAndDescription = "निर्देश",
                installWidget = "विजेट लगाएँ",
                soundSavedNotice = "ध्वनि सेव हो गई है। सेटिंग्स में ध्वनि चुनते समय यह दिखाई देगी.",
                deleteSoundTitle = "ध्वनि हटाएँ?",
                deleteSoundMessage = "यह ध्वनि आपकी ध्वनियों से हटा दी जाएगी। इसे वापस नहीं किया जा सकता.",
                deleteSoundAction = "हटाएँ",
            )
            AppLanguage.ID -> base.copy(
                home = "Beranda",
                settings = "Pengaturan",
                upload = "Unggah",
                profile = "Profil",
                sounds = "Suara",
                fall = "Jatuh",
                slap = "Tamparan",
                sensitivity = "Sensitivitas",
                volume = "Volume",
                language = "Bahasa",
                appLanguage = "Bahasa aplikasi",
                mySounds = "Suara saya",
                library = "Pustaka",
                addSound = "+ tambah suara",
                extractFromVideo = "Ekstrak dari video",
                record = "Rekam",
                uploadFile = "Unggah",
                chooseVideo = "Pilih video",
                chooseAnotherVideo = "Pilih video lain",
                trimCurrentFragment = "Potong fragmen saat ini",
                save = "Simpan",
                cancel = "Batal",
                name = "nama",
                titleLabel = "Nama",
                trimHelp = "Geser slider untuk mengedit",
                fragment = "Fragmen",
                buildingWaveform = "Membuat gelombang...",
                pressToRecord = "Ketuk untuk merekam",
                recording = "Merekam %s",
                firstLaunchTitle = "JANGAN TERBURU-BURU!",
                firstLaunchText = "Agar kesan pertama aplikasi tidak rusak, baca instruksi singkatnya.",
                open = "Buka",
                later = "Nanti",
                modeUnavailable = "mode tidak tersedia",
                modeOn = "mode aktif",
                modeOff = "mode nonaktif",
                guideTitle = "Instruksi",
                guideBody = """
                    1. Coba «Sensitivitas». Sensor bisa berbeda di setiap ponsel. Jika sensitivitas diturunkan sampai minimum, efek tersebut mati sepenuhnya.

                    2. Tambahkan suara sendiri tanpa batas. Kamu bisa merekam, mengunggah hampir semua format dari ponsel, atau mengekstrak audio dari video seperti klip unduhan atau rekaman layar, lalu mengeditnya.

                    3. Kamu bisa memasang widget untuk menyalakan dan mematikan efek dengan cepat.

                    4. Jika ada yang tidak berfungsi atau terasa salah, jangan langsung memberi ulasan buruk: tulis kepada kami dan kami akan menyelesaikannya. Ini aplikasi pertama kami 🙂
                """.trimIndent(),
                guideAndDescription = "Instruksi",
                installWidget = "Pasang widget",
                soundSavedNotice = "Suara disimpan. Suara ini akan muncul di Pengaturan saat memilih suara.",
                deleteSoundTitle = "Hapus suara?",
                deleteSoundMessage = "Suara ini akan dihapus dari Suara saya. Tindakan ini tidak bisa dibatalkan.",
                deleteSoundAction = "Hapus",
            )
            AppLanguage.EN_US -> base
        }

        private val base = AppStrings(
            home = "Home",
            settings = "Settings",
            upload = "Upload",
            profile = "Profile",
            sounds = "Sounds",
            fall = "Fall",
            slap = "Slap",
            sensitivity = "Sensitivity",
            volume = "Volume",
            language = "Language",
            appLanguage = "App language",
            mySounds = "My sounds",
            library = "Library",
            addSound = "+ add sound",
            extractFromVideo = "Extract from video",
            record = "Record",
            uploadFile = "Upload",
            chooseVideo = "Choose video",
            chooseAnotherVideo = "Choose another video",
            trimCurrentFragment = "Trim current fragment",
            save = "Save",
            cancel = "Cancel",
            name = "name",
            titleLabel = "Title",
            trimHelp = "Move the sliders to edit",
            fragment = "Fragment",
            buildingWaveform = "Building waveform...",
            pressToRecord = "Tap to record",
            recording = "Recording %s",
            firstLaunchTitle = "DON'T RUSH!",
            firstLaunchText = "To keep your first impression of the app good, read the short instruction.",
            open = "Open",
            later = "Later",
            modeUnavailable = "mode unavailable",
            modeOn = "mode on",
            modeOff = "mode off",
            guideTitle = "Instruction",
            guideBody = """
                1. Try «Sensitivity». Sensors behave differently on different phones. If you turn sensitivity all the way down, that effect turns off completely.

                2. Add your own sounds without limits. You can record one, upload almost any format from your phone, or extract audio from a video, such as a downloaded clip or screen recording, and edit it.

                3. You can install a widget for quick effect on/off.

                4. If something does not work or feels wrong, please do not rush to leave a bad review. Write to us and we will solve the problem. This is our first app 🙂
            """.trimIndent(),
            guideAndDescription = "Instruction",
            installWidget = "Install widget",
            soundSavedNotice = "Sound saved. It will appear in Settings when you choose a sound.",
            deleteSoundTitle = "Delete sound?",
            deleteSoundMessage = "This sound will be removed from My sounds. This cannot be undone.",
            deleteSoundAction = "Delete",
        )

        private val ru = AppStrings(
            home = "Домой",
            settings = "Настройки",
            upload = "Загрузка",
            profile = "Профиль",
            sounds = "Звуки",
            fall = "Падение",
            slap = "Шлепок",
            sensitivity = "Чувствительность",
            volume = "Громкость",
            language = "Язык",
            appLanguage = "Язык приложения",
            mySounds = "Мои звуки",
            library = "Библиотека",
            addSound = "+ добавить звук",
            extractFromVideo = "Извлечь из видео",
            record = "Записать",
            uploadFile = "Загрузить",
            chooseVideo = "Выбрать видео",
            chooseAnotherVideo = "Выбрать другое видео",
            trimCurrentFragment = "Обрезать текущий фрагмент",
            save = "Сохранить",
            cancel = "Отмена",
            name = "название",
            titleLabel = "Название",
            trimHelp = "Двигай ползунки что бы редактировать",
            fragment = "Фрагмент",
            buildingWaveform = "Строю волну...",
            pressToRecord = "Нажмите для записи",
            recording = "Запись %s",
            firstLaunchTitle = "НЕ СПЕШИ!",
            firstLaunchText = "Чтобы не испортить первое впечатление от приложения, прочти короткую инструкцию",
            open = "Открыть",
            later = "Потом",
            modeUnavailable = "режим недоступен",
            modeOn = "режим включен",
            modeOff = "режим выключен",
            guideTitle = "Инструкция",
            guideBody = """
                1. Покрути «Чувствительность». У разных телефонов датчики ведут себя по-разному. Если убавить чувствительность на минимум, данный эффект выключится полностью.

                2. Добавляй свои звуки без ограничений. Можно записать с диктофона, загрузить с телефона в любом формате или извлечь звук из видео, например из скачанного видео или записи экрана, и отредактировать.

                3. Можно установить виджет для быстрого включения и выключения эффектов.

                4. Если что-то не работает или работает не так, не спешите оставлять плохой отзыв: напишите нам об этом, и мы решим проблему. Это наше первое приложение 🙂
            """.trimIndent(),
            guideAndDescription = "Инструкция",
            installWidget = "Установить виджет",
            soundSavedNotice = "Звук успешно сохранён. Он появится в настройках при выборе звука.",
            deleteSoundTitle = "Удалить звук?",
            deleteSoundMessage = "Этот звук будет удалён из Моих звуков. Отменить действие не получится.",
            deleteSoundAction = "Удалить",
        )
    }
}
